#!bin/sh

echo "---+++---+++---+++---+++---"
echo "Compiling Cython libraries"
echo ""

for path in "clibs" #"plugins/SerpentZeroADGamePlugin/files/api" "plugins/SerpentOzymandiasGameAgentPlugin/files/helpers"
do
    echo ".........compiling........."
    (cd $path && 
    poetry run python setup.py build_ext --inplace &&
    echo "--- --- --- --- --- --- ---" && echo "Compilation Complete"); echo "=== === === === === === ==="
done

echo ""
echo "Finished compiling Cython libraries"
echo "---+++---+++---+++---+++---"
