[tool.poetry]
name = "GameAI"
version = "0.1.0"
description = "Serpent Projects"
authors = ["Nicholas Shindler"]

[tool.poetry.dependencies]
python = "3.6"

[tool.poetry.dev-dependencies]
serpentai = "^2018.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
