SerpentOzymandiasGameAgentPlugin:
  frame_handler: PLAY
SerpentTronGameAgentPlugin:
  frame_handler: PLAY
SerpentTronGamePlugin:
  fps: 2
SerpentZeroADGamePlugin:
  fps: 2
SerpentkapmanGamePlugin:
  fps: 2
